#!/bin/sh

export PATH=/bin:/usr/bin:/sbin:/usr/sbin

adduser --system pixelated --home /var/lib/pixelated --disabled-password --shell /bin/sh --ingroup nogroup
usermod -a -G docker pixelated
usermod -a -G ssl-cert pixelated

mkdir -p /var/lib/pixelated/dispatcher

chown pixelated:nogroup -R /var/lib/pixelated

/etc/init.d/pixelated-dispatcher-manager restart
/etc/init.d/pixelated-dispatcher-proxy restart

